### ISSUE TITLE
there is something wrong

### ISSUE THREAD

**Issue by LeepoYang** [sisinflab/KGFlex#2]
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/KGFlex-master/KGFlex-master/run.py", line 3, in <module>
    run_experiment("config_files/facebook-books_kgflex.yml")
  File "C:\Users\Administrator\Desktop\KGFlex-master\KGFlex-master\elliot\run.py", line 49, in run_experiment
    spec.loader.exec_module(external)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "external\models\__init__.py", line 1, in <module>
    from .kgflex import KGFlex
  File "C:\Users\Administrator\Desktop\KGFlex-master\KGFlex-master\external\models\kgflex\__init__.py", line 1, in <module>
    from .KGFlex import KGFlex
  File "C:\Users\Administrator\Desktop\KGFlex-master\KGFlex-master\external\models\kgflex\KGFlex.py", line 11, in <module>
    from .UserFeatureMapper import UserFeatureMapper
  File "C:\Users\Administrator\Desktop\KGFlex-master\KGFlex-master\external\models\kgflex\UserFeatureMapper.py", line 13, in <module>
    multiprocessing.set_start_method("fork")
  File "C:\ProgramData\Anaconda3\envs\kgflex\lib\multiprocessing\context.py", line 247, in set_start_method
    self._actual_context = self.get_context(method)
  File "C:\ProgramData\Anaconda3\envs\kgflex\lib\multiprocessing\context.py", line 239, in get_context
    return super().get_context(method)
  File "C:\ProgramData\Anaconda3\envs\kgflex\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'

**Comment by albertomancino** [comment]
Hi LeepoYang, did you run your code on Windows? I suggest using Ubuntu to grant that the multiprocessing library works properly.
